goog.provide('domina.support');
goog.require('cljs.core');
goog.require('goog.events');
goog.require('goog.dom');
var div__8704 = document.createElement("div");
var test_html__8705 = "   <link/><table></table><a href='/a' style='top:1px;float:left;opacity:.55;'>a</a><input type='checkbox'/>";
div__8704.innerHTML = test_html__8705;
domina.support.leading_whitespace_QMARK_ = cljs.core._EQ_.call(null,div__8704.firstChild.nodeType,3);
domina.support.extraneous_tbody_QMARK_ = cljs.core._EQ_.call(null,div__8704.getElementsByTagName("tbody").length,0);
domina.support.unscoped_html_elements_QMARK_ = cljs.core._EQ_.call(null,div__8704.getElementsByTagName("link").length,0);
